[package]
name = "dapa-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
dapa-types = { path = "../types" }
dapa-ast = { path = "../ast" }
dapa-environment = { path = "../environment" }
thiserror = "2.0.1"
paste = "1.0.15"
